### ISSUE TITLE
Example doesn't work

### ISSUE THREAD

**Issue by gerchicov-bp** [corin8823/PopupCollectionViewController#4]
$ pod install

[!] Invalid `Podfile` file: [!] Unsupported options `{:exclusive=>true}` for target `PopupCollectionViewControllerExample`..

 #  from /Users/gerchicov/Documents/xCode_projects/PopupCollectionViewController/Example/Podfile:4
 #  -------------------------------------------
 #  

>  target 'PopupCollectionViewControllerExample', :exclusive => true do
>  #    pod 'PopupCollectionViewController', :path => '../'
>  #  -------------------------------------------

**Comment by corin8823** [comment]
Thanks reports!
Please try https://github.com/corin8823/PopupCollectionViewController/releases/tag/0.1.0
